"""002_restrictions

Revision ID: 701ddf864730
Revises: c37a41fc2b5e
Create Date: 2019-01-23 14:08:06.677307

"""
from alembic import context, op
from flask import current_app
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701ddf864730'
down_revision = 'c37a41fc2b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restriction',
    sa.Column('restriction_id', sa.String(), nullable=False),
    sa.Column('restriction_type', sa.String(), nullable=True),
    sa.Column('restriction_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('restriction_id')
    )
    # ### end Alembic commands ###

    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE \"restriction\" TO " +
                    current_app.config.get('APP_SQL_USERNAME'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restriction')
    # ### end Alembic commands ###
